//! Public-API adversarial tests that need PQClean to generate real signatures.
//! Codec-level adversarial tests live inside `solana-falcon512`'s
//! `codec::adversarial` module (no PQClean dep needed there).

use pqcrypto_falcon::falcon512;
use pqcrypto_traits::sign::{DetachedSignature, PublicKey};
use solana_falcon512::{
    FALCON_512_PUBKEY_LEN, FALCON_512_SIGNATURE_LEN, Falcon512Pubkey, Falcon512Signature,
};

// Tiny xorshift64 — deterministic, reproducible.
struct Rng(u64);
impl Rng {
    fn new(seed: u64) -> Self {
        Self(seed | 1)
    }
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        self.0 = x;
        x
    }
}

fn sign(msg: &[u8]) -> ([u8; FALCON_512_PUBKEY_LEN], [u8; FALCON_512_SIGNATURE_LEN]) {
    let (pk, sk) = falcon512::keypair();
    let sig = falcon512::detached_sign(msg, &sk);
    let mut pk_arr = [0u8; FALCON_512_PUBKEY_LEN];
    pk_arr.copy_from_slice(pk.as_bytes());
    let mut sig_arr = [0u8; FALCON_512_SIGNATURE_LEN];
    sig_arr[..sig.as_bytes().len()].copy_from_slice(sig.as_bytes());
    (pk_arr, sig_arr)
}

/// Both verify paths must agree on valid signatures generated by PQClean.
/// Two paths share `norm_check_with_prepared` but diverge on the `n_inv`
/// fold (lib.rs:524 inline vs `prepare_pubkey` separately). Malformed-input
/// rejection is covered by the codec and mutation tests below.
#[test]
fn verify_paths_agree_on_valid_signatures() {
    for i in 0..200u64 {
        let msg = format!("path-symmetry-{}", i);
        let (pk_bytes, sig_bytes) = sign(msg.as_bytes());
        let pk = Falcon512Pubkey::from(pk_bytes);
        let prepared = pk.clone().prepare_pubkey();
        let sig = Falcon512Signature::from(sig_bytes);

        let r1 = sig.verify(msg.as_bytes(), &pk);
        let r2 = sig.verify_with_prepared(msg.as_bytes(), &prepared);
        assert_eq!(
            r1, r2,
            "iter {i}: verify={r1} vs verify_with_prepared={r2} on valid sig"
        );
        assert!(r1, "iter {i}: valid sig rejected");
    }
}

#[test]
fn verify_paths_agree_on_wrong_message() {
    for i in 0..200u64 {
        let msg = format!("wrongmsg-{}", i);
        let (pk_bytes, sig_bytes) = sign(msg.as_bytes());
        let pk = Falcon512Pubkey::from(pk_bytes);
        let prepared = pk.clone().prepare_pubkey();
        let sig = Falcon512Signature::from(sig_bytes);

        let bad_msg = format!("wrongmsg-{}!", i); // appended byte
        let r1 = sig.verify(bad_msg.as_bytes(), &pk);
        let r2 = sig.verify_with_prepared(bad_msg.as_bytes(), &prepared);
        assert_eq!(r1, r2, "iter {i}: paths disagree on wrong-message");
        assert!(!r1, "iter {i}: wrong-message accepted");
    }
}

/// 1000 single-bit mutations of (sig, pk, msg) — both verify paths must
/// return the SAME boolean. Catches any divergence in failure handling
/// (length checks, header rejection, decode failures).
#[test]
fn verify_paths_agree_on_mutated_signatures() {
    let msg = b"adversarial path symmetry test";
    let (pk_bytes, sig_bytes) = sign(msg);
    let pk = Falcon512Pubkey::from(pk_bytes);
    let prepared = pk.clone().prepare_pubkey();

    let mut rng = Rng::new(0xBEEF_FEED_FACE_F00D);
    for iter in 0..1000 {
        let mut mutated_sig = sig_bytes;
        let pos = (rng.next() % FALCON_512_SIGNATURE_LEN as u64) as usize;
        let bit = (rng.next() & 7) as u8;
        mutated_sig[pos] ^= 1 << bit;
        let bad_sig = Falcon512Signature::from(mutated_sig);

        let r1 = bad_sig.verify(msg, &pk);
        let r2 = bad_sig.verify_with_prepared(msg, &prepared);
        assert_eq!(
            r1, r2,
            "iter {iter}: paths disagree on mutated sig (byte {pos} bit {bit}): \
             verify={r1} verify_with_prepared={r2}"
        );
    }
}

/// Pubkey mutation symmetry: comparing `verify` (raw pubkey) vs
/// `verify_with_prepared` (after `prepare_pubkey`) is asymmetric because
/// `prepare_pubkey` is documented to panic on malformed pubkeys. Treat a
/// panic as "rejected" via `catch_unwind`. After that translation, both
/// paths must agree.
#[test]
fn verify_paths_agree_on_mutated_pubkeys_modulo_panic() {
    let msg = b"pubkey mutation symmetry test";
    let (pk_bytes, sig_bytes) = sign(msg);
    let sig = Falcon512Signature::from(sig_bytes);

    let mut rng = Rng::new(0xCAFE_F00D_BEEF_FACE);
    let mut panics = 0u32;
    for iter in 0..1000 {
        let mut mutated_pk = pk_bytes;
        let pos = (rng.next() % FALCON_512_PUBKEY_LEN as u64) as usize;
        let bit = (rng.next() & 7) as u8;
        mutated_pk[pos] ^= 1 << bit;
        let bad_pk = Falcon512Pubkey::from(mutated_pk);

        let r1 = sig.verify(msg, &bad_pk);
        // `prepare_pubkey()` panics on malformed input. Treat panic as reject.
        let bad_pk_clone = bad_pk.clone();
        let r2 = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            let prepared = bad_pk_clone.prepare_pubkey();
            sig.verify_with_prepared(msg, &prepared)
        }))
        .unwrap_or_else(|_| {
            panics += 1;
            false
        });

        assert_eq!(
            r1, r2,
            "iter {iter}: paths disagree on mutated pubkey (byte {pos} bit {bit}) — \
             verify={r1} verify_with_prepared(panic→false)={r2}"
        );
    }
    // Sanity: at least some mutations should hit the assert path. If zero,
    // the test is vacuous.
    assert!(
        panics > 0,
        "no mutations triggered prepare_pubkey panic — test may be vacuous"
    );
}

/// FINDING: `Falcon512Pubkey::prepare_pubkey()` panics on a length-valid but
/// coefficient-malformed pubkey. The README's "runtime prepared pubkey"
/// example uses `try_from(&pk_wire_bytes[..])?.prepare_pubkey()` — and
/// `try_from` validates ONLY length, not coefficient ranges. So a Solana
/// program following that pattern crashes (program error) on any
/// attacker-submitted 897-byte buffer with a coefficient >= Q.
///
/// This is documented at lib.rs:167 ("# Panics") but the README example is
/// inconsistent with that warning. Either:
///   1. Add a `try_prepare_pubkey() -> Result<...>` for runtime use, or
///   2. Have `Falcon512Pubkey::try_from` validate coefficient ranges, or
///   3. Update the README to make the panic risk explicit at the call site.
///
/// This test pins the current behavior so a future change is visible.
#[test]
fn finding_prepare_pubkey_panics_on_malformed_runtime_input() {
    let msg = b"pin current panic behavior";
    let (mut pk_bytes, _) = sign(msg);

    // Construct a length-valid pubkey with a coefficient >= Q.
    // Slot 0 is encoded in the first 14 bits after the 1-byte header,
    // i.e. bits [0..14) of bytes [1..3]. Set those 14 bits to all-1s = 16383
    // which is >= Q (= 12289), invalid.
    pk_bytes[1] = 0xFF;
    pk_bytes[2] |= 0b1111_1100;

    let bad_pk = Falcon512Pubkey::from(pk_bytes);

    // The non-panicking path returns false.
    let sig = Falcon512Signature::from([0u8; FALCON_512_SIGNATURE_LEN]);
    assert!(!sig.verify(msg, &bad_pk));

    // The prepare_pubkey path panics.
    let panicked = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let _ = bad_pk.prepare_pubkey();
    }))
    .is_err();
    assert!(
        panicked,
        "prepare_pubkey did NOT panic on malformed input — \
         either the behavior changed (good!) or the test fixture isn't malformed"
    );
}

/// `try_prepare_pubkey` is the fallible runtime sibling of `prepare_pubkey`.
/// It must accept any valid PQClean-generated pubkey and produce a prepared
/// form byte-equal to what the panicking `prepare_pubkey` produces.
#[test]
fn try_prepare_pubkey_accepts_valid_pubkey() {
    let msg = b"try_prepare_pubkey valid path";
    let (pk_bytes, _) = sign(msg);
    let pk = Falcon512Pubkey::from(pk_bytes);

    let prepared_panicking = pk.clone().prepare_pubkey();
    let prepared_fallible = pk.try_prepare_pubkey().expect("valid pubkey");
    assert_eq!(
        prepared_panicking.as_bytes(),
        prepared_fallible.as_bytes(),
        "fallible and panicking paths produced different prepared pubkeys"
    );
}

/// Wrong header byte: the panicking path crashes; the fallible path returns
/// `Err(InvalidArgument)`.
#[test]
fn try_prepare_pubkey_rejects_bad_header() {
    let msg = b"try_prepare_pubkey bad header";
    let (mut pk_bytes, _) = sign(msg);
    pk_bytes[0] ^= 0xFF; // any non-0x09 byte
    let pk = Falcon512Pubkey::from(pk_bytes);

    let result = pk.try_prepare_pubkey();
    assert!(
        result.is_err(),
        "try_prepare_pubkey accepted a malformed header"
    );
}

/// Out-of-range coefficient (≥ Q): the same fixture that crashes
/// `prepare_pubkey()` (pinned by `finding_prepare_pubkey_panics_on_malformed_runtime_input`)
/// is rejected gracefully by the fallible path.
#[test]
fn try_prepare_pubkey_rejects_out_of_range_coefficient() {
    let msg = b"try_prepare_pubkey out-of-range coeff";
    let (mut pk_bytes, _) = sign(msg);

    // Same construction as `finding_prepare_pubkey_panics_*`: set the first
    // 14-bit-packed coefficient to 0x3FFF (16383) which is >= Q (12289).
    pk_bytes[1] = 0xFF;
    pk_bytes[2] |= 0b1111_1100;

    let pk = Falcon512Pubkey::from(pk_bytes);

    let result = pk.try_prepare_pubkey();
    assert!(
        result.is_err(),
        "try_prepare_pubkey accepted a coefficient >= Q"
    );
}

/// Empty-message edge case: nonce is 40 bytes, msg is 0 bytes. SHAKE
/// finalize position is exactly 40 (mid-lane in lane 5). Verifies the
/// finalize path handles this without producing a divergent c[].
#[test]
fn verify_handles_empty_message() {
    let (pk_bytes, sig_bytes) = sign(b"");
    let pk = Falcon512Pubkey::from(pk_bytes);
    let prepared = pk.clone().prepare_pubkey();
    let sig = Falcon512Signature::from(sig_bytes);
    assert!(sig.verify(b"", &pk));
    assert!(sig.verify_with_prepared(b"", &prepared));
    // Wrong-message check: a non-empty message must reject.
    assert!(!sig.verify(b"x", &pk));
    assert!(!sig.verify_with_prepared(b"x", &prepared));
}

/// Long-message edge case: forces SHAKE absorb to span many rate blocks.
#[test]
fn verify_handles_long_message() {
    let msg: Vec<u8> = (0..10_000u32).map(|i| (i & 0xFF) as u8).collect();
    let (pk_bytes, sig_bytes) = sign(&msg);
    let pk = Falcon512Pubkey::from(pk_bytes);
    let prepared = pk.clone().prepare_pubkey();
    let sig = Falcon512Signature::from(sig_bytes);
    assert!(sig.verify(&msg, &pk));
    assert!(sig.verify_with_prepared(&msg, &prepared));
}

/// Header-byte rejection: every non-`0x39` first byte must reject.
/// Belt-and-suspenders against a future change that softens the header check.
#[test]
fn rejects_every_non_compressed_header() {
    let msg = b"header rejection";
    let (pk_bytes, sig_bytes) = sign(msg);
    let pk = Falcon512Pubkey::from(pk_bytes);
    let prepared = pk.clone().prepare_pubkey();

    for hdr in 0u8..=255 {
        if hdr == 0x39 {
            continue;
        } // valid header
        let mut tampered = sig_bytes;
        tampered[0] = hdr;
        let bad = Falcon512Signature::from(tampered);
        assert!(
            !bad.verify(msg, &pk),
            "verify accepted header byte {hdr:#x}"
        );
        assert!(
            !bad.verify_with_prepared(msg, &prepared),
            "verify_with_prepared accepted header byte {hdr:#x}"
        );
    }
}

#[test]
fn rejects_every_non_pubkey_header() {
    let msg = b"pubkey header rejection";
    let (pk_bytes, sig_bytes) = sign(msg);
    let sig = Falcon512Signature::from(sig_bytes);

    for hdr in 0u8..=255 {
        if hdr == 0x09 {
            continue;
        } // valid header
        let mut tampered_pk = pk_bytes;
        tampered_pk[0] = hdr;
        let bad_pk = Falcon512Pubkey::from(tampered_pk);
        assert!(
            !sig.verify(msg, &bad_pk),
            "accepted pubkey header byte {hdr:#x}"
        );
    }
}
